# Generated by Django 3.1.4 on 2020-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201218_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_text',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply_timestamp',
            new_name='comment_timestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_profile_pic.png', upload_to='blog_covers'),
        ),
    ]
